Revert 274310 "Introduce IPC::ChannelProxy::Create*() and IPC::S..."
Broke Windows compile:
http://build.chromium.org/p/chromium.win/buildstatus?builder=Win%20x64%20Builder&number=180

FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\remoting\host\win\remoting_core.wts_session_process_delegate.obj.rsp /c ..\..\remoting\host\win\wts_session_process_delegate.cc /Foobj\remoting\host\win\remoting_core.wts_session_process_delegate.obj /Fdobj\remoting\remoting_core.cc.pdb 
c:\b\build\slave\win_x64_builder\build\src\remoting\host\win\wts_session_process_delegate.cc(386) : error C2661: 'IPC::ChannelProxy::ChannelProxy' : no overloaded function takes 4 arguments
ninja: build stopped: subcommand failed.


> Introduce IPC::ChannelProxy::Create*() and IPC::SynChannel::Create*()
> 
> This change hides constructors of these classes so that we can turn
> them polymorphic classes.
> 
> Note that having almost identical ChannelProxy::Init*() isn't great
> and they will be replaced by a factory-like abstraction in coming
> changes.
> 
> TEST=none
> R=darin,cpu
> BUG=377980
> 
> Review URL: https://codereview.chromium.org/301973003

TBR=morrita@chromium.org

Review URL: https://codereview.chromium.org/312553004

git-svn-id: http://src.chromium.org/svn/trunk/src/chrome/browser@274315 4ff67af0-8c30-449e-8e8b-ad334ec8d88c